### ISSUE TITLE
License of repetier-cncplugin

### ISSUE THREAD

**Issue by Lunavast** [ahd71/repetier-cncplugin#13]
Hi,

What is the license of repetier-cncplugin?
Can we fork (modify) and publish with the copyright notice of "Hellstrand"?
I have a plan to make a repetier plugin based on repetier-cncplugin though it is not for CNC.

**Comment by ahd71** [comment]
Hi,

Thanks for asking. I've added a license section in the readme to clarify this.

## Licence

Released under Creative Common with attribution 4.0 (CC BY). In short that allows you to fork and remix as long as a reference to the original source/author is mentioned - preferable by linking to https://github.com/ahd71/repetier-cncplugin

BR/Anders

**Comment by Lunavast** [comment]
Thank you for the reply and clarifying about the license.
